env:
  browser: true
  es2021: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {}
