---
version: '3'
includes:
  greeting: '.tasks/helloworld.yaml'
  js: 
    taskfile: '.tasks/lang/javascript/js.yaml'
    dir: './.tasks/lang/javascript/js.yaml'
  go:
    taskfile: '.tasks/lang/go/go.yaml'
    dir: './.tasks/lang/go/go.yaml'

# tasks:
#   default:
#     cmds:
#       - task --list-all
#     silent: true
