---
version: '3'
includes:
  js:
    taskfile: './.tasks/lang/javascript/js.yaml'
    dir: './services/frontend-app'
  go:
    taskfile: './.tasks/lang/go/go.yaml'
    dir: './services/backend-app'

# tasks:
#   default:
#     cmds:
#       - task --list-all
#     silent: true
